### ISSUE TITLE
Fail on DREDS-CatKnown Test Data Download and Fail on Inference on DREDS-CatKnown Val and STD-CatKnown

### ISSUE THREAD

**Issue by ZhangCYG** [PKU-EPIC/DREDS#4]
Thanks for your impressive first. But I have 2 intractable problems about your released code.

First, using your download shell for DREDS-CatKnown Test Data, what I've got is only a file than a folder after gunzip your test.gz file. I think the file link may be wrong.
![image](https://user-images.githubusercontent.com/62829225/187150536-01a22cb0-41e2-46c7-838e-61ecac0a8e65.png)

Second, when I try to use inference.py to run on DREDS-CatKnown Val and STD-CatKnown dataset to check the result on the paper, I've found some errors.

My order is like: python inference.py --val_data_type real --train_data_path data/DREDS/DREDS-CatKnown/train --val_data_path data/STD/STD-CatKnown  --val_obj_path data/cad_model/real_cat_known --val_depth_path data/STD/STD-CatKnown.

And the error is:
![image](https://user-images.githubusercontent.com/62829225/187150481-ab425dda-6b98-4d34-8396-f586cb63e3af.png)

I would appreciate it if you can solve the 2 problems I met!

**Comment by qiweili00** [comment]
For the second problem, you can comment out **save_path** in [https://github.com/PKU-EPIC/DREDS/blob/8c17bfa91bfe7f3aba6314a2ce658cd12df8b1e7/CatePoseEstimation/trainer.py#L1357](url) and [https://github.com/PKU-EPIC/DREDS/blob/8c17bfa91bfe7f3aba6314a2ce658cd12df8b1e7/CatePoseEstimation/trainer.py#L1345](url).
We will update code later.

**Comment by Daiqy** [comment]
Hi! For the first problem, please extract the downloaded _test.gz_ using _tar -xvf test.gz_ instead of _gzip -d test.gz_.
