### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:

### ISSUE THREAD

**Issue by rnlee1998** [PKU-EPIC/DREDS#6]
Errors occur when I run train.py and how should I do ?

```py
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    _trainer.train()
  File "/data/ran1998.li/workdir/DREDS-main/SwinDRNet/trainer.py", line 706, in train
    self.loss_train_iter.backward()
  File "/home/ran1998.li/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ran1998.li/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 512, 14, 14]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

**Comment by wenzhoulyu** [comment]
I meet the same problem. how can you deal with it?

> Errors occur when I run train.py and how should I do ?
> 
> ```python
> Traceback (most recent call last):
>   File "train.py", line 110, in <module>
>     _trainer.train()
>   File "/data/ran1998.li/workdir/DREDS-main/SwinDRNet/trainer.py", line 706, in train
>     self.loss_train_iter.backward()
>   File "/home/ran1998.li/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/home/ran1998.li/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
>     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 512, 14, 14]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
> ```
