### ISSUE TITLE
About inference time

### ISSUE THREAD

**Issue by rnlee1998** [PKU-EPIC/DREDS#7]
Hello, I appreciate your work and I have a question about the inference time. In your paper, SwinDRNet allows real-time depth restoration(30FPS).

However, I only get 0.376s per frame when I modify the inference.py (126 line) are as follows.
```py
    begin = time.time()
    metrics_instance, metrics_background, outputs_depth_list = _trainer.inference()
    end = time.time()
    print((end-begin)/len(_trainer.val_loader))
```

**Comment by Daiqy** [comment]
Hi rnlee1998! Please check whether batch size = 1 when in inference. Furthermore, we evaluate all methods in our paper on NVIDIA RTX 3090 GPU, and only consider the network forward propagation without any other processing like data loading, metric calculating, or result saving when computing time. Thank you!
