### ISSUE TITLE
关于修改渲染脚本的问题

### ISSUE THREAD

**Issue by ZhiyangZhou24** [PKU-EPIC/DREDS#9]
非常感谢作者能够开源这么优秀的工作，我想请教一个问题。如何修改DepthSensorSimulator中提供的renderer.py脚本，以达到生成只包含透明物体的场景（场景中只保留透明物体）呢？

**Comment by Daiqy** [comment]
Hi! Please set _my_material_randomize_mode_ to _transparent_, and write all categories to the key _transparent_ of _class_material_pairs_.
